### ISSUE TITLE
⭐ Update 1.0.0. Custom compiler. YML for meta file. Multiple resources. Bundling

### ISSUE THREAD

**Issue by Toliak** [mtasa-typescript/mtasa-lua-utils#26]
**Description**

The global update **1.0.0** should provide features listed below:
- TSTL Compiler wrapper
- Bundle files and non-bundled files support (see #24)
- Multi-resource support (see #19)
- YML format for meta file
- Rewritten plugins from ttypescript into the [tstl visitors](https://typescripttolua.github.io/docs/api/plugins)

**Comment by Toliak** [comment]
### New way of creating the resource

Provide the ability to run one command instead of downloading the boilerplate.
Look at [npx](https://medium.com/devschacht/introducing-npx-an-npm-package-runner-a72a658cd9e6)

**Comment by Toliak** [comment]
- [ ] Provide an ability to import enums or interfaces from an another resource
- [ ] Check: do not allow to import functions, variables, classes from another resource
- [ ] Check: exported (in meta) function should exist
